# Generated by Django 5.1.7 on 2025-04-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('horaInicio', models.TimeField(blank=True, null=True, verbose_name='H.Inicio')),
                ('horaFin', models.TimeField(blank=True, null=True, verbose_name='H.Fin')),
                ('idTipTarea', models.IntegerField(blank=True, null=True, verbose_name='Tip.Tarea')),
                ('idTipArticulo', models.IntegerField(blank=True, null=True, verbose_name='Tip.Articulo')),
                ('idOper1', models.IntegerField(blank=True, null=True, verbose_name='Op.1')),
                ('idOper2', models.IntegerField(blank=True, null=True, verbose_name='Op.2')),
                ('cantidad', models.IntegerField(blank=True, null=True, verbose_name='Cantidad')),
            ],
        ),
    ]
