# Generated by Django 5.1.7 on 2025-04-10 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patio',
            name='idTipArticulo',
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codBarrasPaquete', models.IntegerField(blank=True, null=True, verbose_name='Cod.Barras')),
                ('idTipArticulo', models.IntegerField(blank=True, null=True, verbose_name='Tip.Articulo')),
                ('cantidad_paquete', models.IntegerField(blank=True, null=True, verbose_name='Cantidad paquete')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquetes', to='pda.patio')),
            ],
        ),
    ]
