# Generated by Django 5.1.7 on 2025-04-21 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pda', '0002_remove_patio_idtiparticulo_paquete'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbaranDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True, verbose_name='Num.Albaran')),
            ],
        ),
        migrations.CreateModel(
            name='LineaArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idArticulo', models.IntegerField(verbose_name='Id.Artiulo')),
                ('cantidad_buena', models.IntegerField(default=0, verbose_name='Cantidad buena')),
                ('cantidad_mala', models.IntegerField(default=0, verbose_name='Cantidad mala')),
                ('chatarra', models.IntegerField(default=0, verbose_name='Chatarra')),
                ('albaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='pda.albarandevolucion')),
            ],
        ),
    ]
