# Generated by Django 5.1.7 on 2025-04-21 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pda', '0003_albarandevolucion_lineaarticulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='albarandevolucion',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
    ]
