# Generated by Django 5.1.7 on 2025-04-21 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pda', '0004_albarandevolucion_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albarandevolucion',
            name='fecha',
        ),
    ]
