# Generated by Django 5.1.7 on 2025-04-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pda', '0005_remove_albarandevolucion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineaarticulo',
            name='idArticulo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
