# Generated by Django 5.1.7 on 2025-04-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pda', '0006_alter_lineaarticulo_idarticulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineaarticulo',
            name='cantidad_buena',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lineaarticulo',
            name='cantidad_mala',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lineaarticulo',
            name='chatarra',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
