# Generated by Django 5.1.7 on 2025-04-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pda', '0007_alter_lineaarticulo_cantidad_buena_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='horaFin',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Fin'),
        ),
        migrations.AddField(
            model_name='paquete',
            name='horaInicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Inicio'),
        ),
    ]
