# Generated by Django 5.1.7 on 2025-04-28 09:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pda', '0009_articulo_tipotarea_trabajador'),
    ]

    operations = [
        migrations.AddField(
            model_name='albarandevolucion',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
