# Generated by Django 5.1.7 on 2025-04-28 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pda', '0010_albarandevolucion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albarandevolucion',
            name='fecha',
            field=models.DateField(default=datetime.date(2025, 4, 28)),
        ),
    ]
