# Generated by Django 5.1.7 on 2025-04-30 07:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pda', '0011_alter_albarandevolucion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albarandevolucion',
            name='fecha',
            field=models.DateField(default=datetime.date(2025, 4, 30)),
        ),
        migrations.AlterField(
            model_name='patio',
            name='idTipTarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pda.tipotarea'),
        ),
    ]
