# Generated by Django 5.1.7 on 2025-04-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pda', '0012_alter_albarandevolucion_fecha_alter_patio_idtiptarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patio',
            name='idTipTarea',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tip.Tarea'),
        ),
    ]
