# Generated by Django 5.1.7 on 2025-05-09 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pda', '0013_alter_patio_idtiptarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipotarea',
            name='cod_tarea',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='albarandevolucion',
            name='fecha',
            field=models.DateField(default=datetime.date(2025, 5, 9)),
        ),
    ]
