# Generated by Django 5.1.7 on 2025-05-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pda', '0014_tipotarea_cod_tarea_alter_albarandevolucion_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='apellidos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
