# Generated by Django 5.1.7 on 2025-05-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pda', '0015_articulo_apellidos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='apellidos',
        ),
        migrations.AddField(
            model_name='trabajador',
            name='apellidos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
