# Generated by Django 5.1.7 on 2025-05-12 07:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pda', '0016_remove_articulo_apellidos_trabajador_apellidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albarandevolucion',
            name='fecha',
            field=models.DateField(default=datetime.date(2025, 5, 12)),
        ),
        migrations.AlterField(
            model_name='patio',
            name='idTipTarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='pda.tipotarea'),
        ),
    ]
