# Generated by Django 5.1.7 on 2025-05-13 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pda', '0018_alter_patio_idtiptarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Andalucia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tot_unid', models.IntegerField(blank=True, null=True)),
                ('p_alq_medio', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cataluña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tot_unid', models.IntegerField(blank=True, null=True)),
                ('p_alq_medio', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Levante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tot_unid', models.IntegerField(blank=True, null=True)),
                ('p_alq_medio', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Madrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tot_unid', models.IntegerField(blank=True, null=True)),
                ('p_alq_medio', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='albarandevolucion',
            name='fecha',
            field=models.DateField(default=datetime.date(2025, 5, 13)),
        ),
    ]
