# Generated by Django 5.1.7 on 2025-05-13 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pda', '0019_andalucia_cataluña_levante_madrid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='andalucia',
            name='articulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineas_andalucia', to='pda.articulo'),
        ),
        migrations.AddField(
            model_name='cataluña',
            name='articulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineas_cataluña', to='pda.articulo'),
        ),
        migrations.AddField(
            model_name='levante',
            name='articulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineas_levante', to='pda.articulo'),
        ),
        migrations.AddField(
            model_name='madrid',
            name='articulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineas_madrid', to='pda.articulo'),
        ),
    ]
