# Generated by Django 5.1.7 on 2025-05-14 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pda', '0020_andalucia_articulo_cataluña_articulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albarandevolucion',
            name='fecha',
            field=models.DateField(default=datetime.date(2025, 5, 14)),
        ),
        migrations.AlterField(
            model_name='andalucia',
            name='p_alq_medio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cataluña',
            name='p_alq_medio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='levante',
            name='p_alq_medio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='madrid',
            name='p_alq_medio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
