# Generated by Django 5.1.7 on 2025-05-20 14:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pda', '0021_alter_albarandevolucion_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albarandevolucion',
            name='fecha',
            field=models.DateField(default=datetime.date(2025, 5, 20)),
        ),
        migrations.CreateModel(
            name='Costes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('Articulo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articulo', to='pda.articulo')),
            ],
        ),
    ]
