# Generated by Django 5.1.7 on 2025-05-21 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pda', '0022_alter_albarandevolucion_fecha_costes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costes',
            old_name='Articulo',
            new_name='articulo',
        ),
        migrations.AlterField(
            model_name='albarandevolucion',
            name='fecha',
            field=models.DateField(default=datetime.date(2025, 5, 21)),
        ),
        migrations.AlterField(
            model_name='costes',
            name='precio',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
