# Generated by Django 5.1.7 on 2025-05-21 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pda', '0023_rename_articulo_costes_articulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costes',
            name='articulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costes', to='pda.articulo'),
        ),
    ]
